plot3 <- plot(dt$timestamp,dt$Sub_metering_1,type = "l" ,ylab = "Energy sub metering" ,xlab = "")
lines(dt$timestamp,dt$Sub_metering_2,col="red")
lines(dt$timestamp,dt$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1),cex=.5)
dev.copy(png, file="./ExData_Plotting1/plot3.png", width=480, height=480)
dev.off()