par(mfrow=c(2,2))
plot(dt$timestamp,dt$Global_active_power,type = "l" ,ylab = "Global Active Power (kilowatts)" ,xlab = "")
plot(dt$timestamp,dt$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dt$timestamp,dt$Sub_metering_1,type = "l" ,ylab = "Energy sub metering" ,xlab = "")
lines(dt$timestamp,dt$Sub_metering_2,col="red")
lines(dt$timestamp,dt$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), cex=.5, bty="n")
plot(dt$timestamp,dt$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.copy(png, file="./ExData_Plotting1/plot4.png", width=480, height=480)
dev.off()